# Generated by Django 2.2.3 on 2019-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
