# Generated by Django 2.2.3 on 2019-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazinePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='magazines/thumbnails/')),
                ('document', models.FileField(upload_to='magazines/epub/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.TextField(default=None)),
            ],
        ),
    ]
