# Generated by Django 2.2.3 on 2019-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinepost',
            name='file',
            field=models.TextField(default=None, null=True),
        ),
    ]
