# Generated by Django 2.2.3 on 2019-09-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20190910_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinepost',
            name='file',
        ),
    ]
