# Generated by Django 2.2.3 on 2019-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_remove_magazinepost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinepost',
            name='file',
            field=models.TextField(default=None, null=True),
        ),
    ]
