# Generated by Django 2.2.3 on 2019-08-11 21:37

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_auto_20190811_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='priority',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 21, 37, 23, 890040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(upload_to='adds/images/'),
        ),
    ]
