# Generated by Django 2.2.3 on 2019-08-11 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_auto_20190811_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 21, 55, 8, 925912, tzinfo=utc)),
        ),
    ]
