# Generated by Django 2.2.3 on 2019-08-11 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_auto_20190811_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 22, 3, 36, 407763, tzinfo=utc)),
        ),
    ]
