# Generated by Django 2.2.3 on 2019-08-11 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0006_auto_20190811_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 22, 5, 37, 330488, tzinfo=utc)),
        ),
    ]
