# Generated by Django 2.2.3 on 2019-08-12 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0007_auto_20190811_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 0, 39, 32, 874809, tzinfo=utc)),
        ),
    ]
