# Generated by Django 2.2.3 on 2019-08-12 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0008_auto_20190812_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 10, 30, 12, 602473, tzinfo=utc)),
        ),
    ]
