# Generated by Django 2.2.3 on 2019-08-14 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0013_auto_20190814_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 13, 49, 20, 578866, tzinfo=utc)),
        ),
    ]
