# Generated by Django 2.2.3 on 2019-08-16 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0015_auto_20190815_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 28, 34, 229829, tzinfo=utc)),
        ),
    ]
