# Generated by Django 2.2.3 on 2019-08-16 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0016_auto_20190816_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 15, 45, 49, 465268, tzinfo=utc)),
        ),
    ]
