# Generated by Django 2.2.3 on 2019-08-16 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0017_auto_20190816_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 16, 45, 23, 674177, tzinfo=utc)),
        ),
    ]
