# Generated by Django 2.2.3 on 2019-08-16 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0018_auto_20190816_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 18, 46, 2, 679842, tzinfo=utc)),
        ),
    ]
