# Generated by Django 2.2.3 on 2019-08-20 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0020_auto_20190818_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 14, 50, 9, 562561, tzinfo=utc)),
        ),
    ]
