# Generated by Django 2.2.3 on 2019-08-20 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0021_auto_20190820_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 14, 57, 51, 861760, tzinfo=utc)),
        ),
    ]
