# Generated by Django 2.2.3 on 2019-08-20 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0030_auto_20190820_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 20, 51, 47, 575633, tzinfo=utc)),
        ),
    ]
