# Generated by Django 2.2.3 on 2019-08-22 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0034_auto_20190822_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 19, 28, 52, 96203, tzinfo=utc)),
        ),
    ]
