# Generated by Django 2.2.3 on 2019-08-26 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0035_auto_20190822_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 16, 22, 52, 514528, tzinfo=utc)),
        ),
    ]
