# Generated by Django 2.2.3 on 2019-09-07 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0036_auto_20190826_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 8, 27, 16, 755733, tzinfo=utc)),
        ),
    ]
