# Generated by Django 2.2.3 on 2019-09-10 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0044_auto_20190910_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 11, 22, 40, 13381, tzinfo=utc)),
        ),
    ]
